name: my_counter_app
description: A simple counter app with custom calculation, sound, vibration, popup window, and YouTube floating player.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.1.2
  vibration: ^1.7.4
  audioplayers: ^5.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/click.mp3
    
